language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo pip install --upgrade pip
  
install:
  - sudo apt-get install g++-4.8 valgrind libboost-all-dev gcov
  - sudo pip install cpp-coveralls

script:
  - make valgrind -C cpp
  
after_success:
  - gcov --version
  - coveralls -b cpp

