language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install: 
  - pip install flake8
  - sudo apt-get install g++-4.8

before_script:
  - flake8 .
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then (make -C cpp); fi

script: 
  - py.test
