language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  
install:
  - sudo apt-get install g++-4.8 valgrind libboost-all-dev

script:
  - make valgrind -C cpp
