language: cpp

before_install:
  - add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - apt-get update
  - pip install --upgrade pip
  
install:
  - apt-get install g++ valgrind libboost-all-dev
  - pip install cpp-coveralls

script:
  - make valgrind -C cpp
  
after_success:
  - coveralls -b cpp

