language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; sudo apt-get update; fi
  
install: 
  - pip install flake8

before_script:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then make -C cpp; fi
  - flake8 .

script: 
  - py.test
